spring:
  application:
    name: weathermate
  
  datasource:
    url: jdbc:h2:mem:weathermate
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
  
  cache:
    type: simple
    cache-names: weather-data
  
  # 한글 인코딩 강제 설정
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  
  # Jackson 설정
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

# Bean 오버라이딩 허용
main:
  allow-bean-definition-overriding: true
  
server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
logging:
  level:
    com.weathermate: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework.web.servlet: DEBUG


# OpenWeather API 설정
openweather:
  api:
    key: ${OPENWEATHER_API_KEY:여기에_새로운_API_키_입력}
    base-url: https://api.openweathermap.org/data/2.5
    cache-duration-minutes: 10

# Mock 데이터 설정 (API 키 없을 때 사용)
weather:
  mock:
    enabled: true  # API 키가 없을 때 true로 설정

